// Adapted from Chr0mX/rustdesk's flutter/web/js/src/common.ts (v1,
// recovered in Phase 2). sleep() is a straight port; mapKey() is now a
// straight port too (see KEY_MAP below) - the rest still need
// dependencies this webclient doesn't have yet, see README.md.
import * as message from './message'

export async function sleep (ms) {
  await new Promise((r) => setTimeout(r, ms))
}

// Hand-vendored from rustdesk-api's own legacy v1 webclient source
// (resources/web/js/src/gen_js_from_hbb.ts's KEY_MAP export, itself
// generated by that same directory's gen_js_from_hbb.py by parsing the
// real rustdesk client's src/client.rs KEY_MAP constant) - the exact
// "hand-vendor a small snapshot of just this constant" plan from
// docs/WEBCLIENT_V2_REBUILD_PLAN.md's "Why this is tractable" section.
// input_model.dart's legacy keyboard path sends key names from this same
// vocabulary (VK_* Windows-style virtual-key names, plus a handful of
// bare names for keys with no VK_ equivalent - Meta/RAlt/RWin/RControl/
// RShift/Apps/CTRL_ALT_DEL/LOCK_SCREEN), confirmed by curConn.js's own
// pre-existing modifier-cancellation checks (`name === 'VK_MENU'`,
// `name === 'RAlt'`, etc. in inputKey()) already assuming this exact
// vocabulary before this table existed to back it.
//
// IMPORTANT: without this table, mapKey() always returned undefined and
// inputKey() silently no-op'ed on every keystroke (`if (!key_event)
// return`) - Legacy-mode keyboard input (the default, and the only
// keyboard mode previously marked "working" in the feature audit) was
// completely non-functional before this fix, despite mouse/video/audio
// all working. Re-audited and corrected.
const KEY_MAP = {
  VK_A: 'a', VK_B: 'b', VK_C: 'c', VK_D: 'd', VK_E: 'e', VK_F: 'f', VK_G: 'g',
  VK_H: 'h', VK_I: 'i', VK_J: 'j', VK_K: 'k', VK_L: 'l', VK_M: 'm', VK_N: 'n',
  VK_O: 'o', VK_P: 'p', VK_Q: 'q', VK_R: 'r', VK_S: 's', VK_T: 't', VK_U: 'u',
  VK_V: 'v', VK_W: 'w', VK_X: 'x', VK_Y: 'y', VK_Z: 'z',
  VK_0: '0', VK_1: '1', VK_2: '2', VK_3: '3', VK_4: '4', VK_5: '5', VK_6: '6',
  VK_7: '7', VK_8: '8', VK_9: '9',
  VK_COMMA: ',', VK_SLASH: '/', VK_SEMICOLON: ';', VK_QUOTE: "'",
  VK_LBRACKET: '[', VK_RBRACKET: ']', VK_BACKSLASH: '\\', VK_MINUS: '-', VK_PLUS: '=',
  VK_DIVIDE: 'Divide', VK_MULTIPLY: 'Multiply', VK_SUBTRACT: 'Subtract', VK_ADD: 'Add', VK_DECIMAL: 'Decimal',
  VK_F1: 'F1', VK_F2: 'F2', VK_F3: 'F3', VK_F4: 'F4', VK_F5: 'F5', VK_F6: 'F6',
  VK_F7: 'F7', VK_F8: 'F8', VK_F9: 'F9', VK_F10: 'F10', VK_F11: 'F11', VK_F12: 'F12',
  VK_ENTER: 'Return', VK_CANCEL: 'Cancel', VK_BACK: 'Backspace', VK_TAB: 'Tab',
  VK_CLEAR: 'Clear', VK_RETURN: 'Return', VK_SHIFT: 'Shift', VK_CONTROL: 'Control',
  VK_MENU: 'Alt', VK_PAUSE: 'Pause', VK_CAPITAL: 'CapsLock', VK_KANA: 'Kana',
  VK_HANGUL: 'Hangul', VK_JUNJA: 'Junja', VK_FINAL: 'Final', VK_HANJA: 'Hanja',
  VK_KANJI: 'Kanji', VK_ESCAPE: 'Escape', VK_CONVERT: 'Convert', VK_SPACE: 'Space',
  VK_PRIOR: 'PageUp', VK_NEXT: 'PageDown', VK_END: 'End', VK_HOME: 'Home',
  VK_LEFT: 'LeftArrow', VK_UP: 'UpArrow', VK_RIGHT: 'RightArrow', VK_DOWN: 'DownArrow',
  VK_SELECT: 'Select', VK_PRINT: 'Print', VK_EXECUTE: 'Execute', VK_SNAPSHOT: 'Snapshot',
  VK_INSERT: 'Insert', VK_DELETE: 'Delete', VK_HELP: 'Help', VK_SLEEP: 'Sleep',
  VK_SEPARATOR: 'Separator',
  VK_NUMPAD0: 'Numpad0', VK_NUMPAD1: 'Numpad1', VK_NUMPAD2: 'Numpad2', VK_NUMPAD3: 'Numpad3',
  VK_NUMPAD4: 'Numpad4', VK_NUMPAD5: 'Numpad5', VK_NUMPAD6: 'Numpad6', VK_NUMPAD7: 'Numpad7',
  VK_NUMPAD8: 'Numpad8', VK_NUMPAD9: 'Numpad9',
  Apps: 'Apps', Meta: 'Meta', RAlt: 'RAlt', RWin: 'RWin', RControl: 'RControl', RShift: 'RShift',
  CTRL_ALT_DEL: 'CtrlAltDel', LOCK_SCREEN: 'LockScreen',
}

const zCode = 'z'.charCodeAt(0)
const aCode = 'a'.charCodeAt(0)

export function mapKey (name, isDesktop) {
  const tmp = KEY_MAP[name] || name
  if (tmp.length === 1) {
    const chr = tmp.charCodeAt(0)
    if (!isDesktop && (chr > zCode || chr < aCode)) return message.KeyEvent.fromPartial({ unicode: chr })
    return message.KeyEvent.fromPartial({ chr })
  }
  const control_key = message.controlKeyFromJSON(tmp)
  if (control_key === message.ControlKey.UNRECOGNIZED) {
    console.error('Unknown control key ' + tmp)
  }
  return message.KeyEvent.fromPartial({ control_key })
}

// Needs the zstd wasm decoder (v1 used the "zstddec" npm package) - not
// yet added as a dependency.
export async function decompress (compressedArray) {
  console.warn('decompress() not yet implemented - needs a zstd wasm decoder dependency')
  return undefined
}

// Needs LANGS, from the same gen_js_from_hbb.py output as mapKey's
// KEY_MAP above.
export function translate (locale, text) {
  return text
}
