// Adapted from Chr0mX/rustdesk's flutter/web/js/src/common.ts (v1,
// recovered in Phase 2). Only sleep() is a straight port - the rest need
// dependencies this webclient doesn't have yet, see README.md.

export async function sleep (ms) {
  await new Promise((r) => setTimeout(r, ms))
}

// v1's mapKey() looked up KEY_MAP[name] - generated by v1's
// gen_js_from_hbb.py from the actual rustdesk client's src/client.rs
// constants (see docs/WEBCLIENT_V2_REBUILD_PLAN.md's "Why this is
// tractable": the plan is to hand-vendor a small snapshot of just this
// constant, not take a live dependency on Chr0mX/rustdesk's Rust source
// from this repo). Needs message.js's KeyEvent/ControlKey too (protobuf
// codegen, see websock.js's header comment) - can't be implemented at all
// until both of those exist.
export function mapKey (name, isDesktop) {
  console.warn(`mapKey("${name}") not yet implemented - needs KEY_MAP (vendor from client.rs) and message.js (protobuf codegen)`)
  return undefined
}

// Needs the zstd wasm decoder (v1 used the "zstddec" npm package) - not
// yet added as a dependency.
export async function decompress (compressedArray) {
  console.warn('decompress() not yet implemented - needs a zstd wasm decoder dependency')
  return undefined
}

// Needs LANGS, from the same gen_js_from_hbb.py output as mapKey's
// KEY_MAP above.
export function translate (locale, text) {
  return text
}
